const PDFDocument = require('pdfkit');
const ApiError = require('../utils/ApiError');
const {
  Grade,
  Student,
  User,
  SchoolClass,
  Subject,
  Attendance,
  ReportCard
} = require('../models');

function formatName(user) {
  return `${user.firstName} ${user.lastName}`;
}

async function buildReportCard(studentId, term, session, generatedBy = null) {
  const student = await Student.findByPk(studentId, {
    include: [
      { model: User, as: 'user' },
      { model: SchoolClass, as: 'class' }
    ]
  });

  if (!student) throw new ApiError(404, 'Student not found');

  const grades = await Grade.findAll({
    where: { studentId, term, session },
    include: [{ model: Subject, as: 'subject' }],
    order: [[{ model: Subject, as: 'subject' }, 'name', 'ASC']]
  });

  const total = grades.reduce((sum, grade) => sum + Number(grade.totalScore), 0);
  const average = grades.length ? Number((total / grades.length).toFixed(2)) : 0;
  const remarks = average >= 70 ? 'Excellent performance'
    : average >= 60 ? 'Very good progress'
      : average >= 50 ? 'Good effort'
        : average >= 40 ? 'Fair result, improvement encouraged'
          : 'Needs steady academic support';

  const attendanceTotal = await Attendance.count({ where: { studentId } });
  const attendancePresent = await Attendance.count({
    where: { studentId, status: ['present', 'late'] }
  });

  const report = await ReportCard.upsert({
    studentId,
    classId: student.classId,
    term,
    session,
    averageScore: average,
    remarks,
    generatedBy
  });

  return {
    reportCardId: Array.isArray(report) ? report[0]?.id : null,
    student: {
      id: student.id,
      admissionNumber: student.admissionNumber,
      name: formatName(student.user),
      class: student.class.name
    },
    term,
    session,
    subjects: grades.map((grade) => ({
      subject: grade.subject.name,
      assessmentScore: Number(grade.assessmentScore),
      examScore: Number(grade.examScore),
      totalScore: Number(grade.totalScore),
      grade: grade.grade,
      remarks: grade.remarks
    })),
    average,
    remarks,
    attendance: {
      present: attendancePresent,
      total: attendanceTotal,
      percentage: attendanceTotal ? Math.round((attendancePresent / attendanceTotal) * 100) : 0
    }
  };
}

function generateReportCardPdf(data) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).text('Smart School Manager', { align: 'center' });
    doc.moveDown(0.25);
    doc.fontSize(14).text('Student Report Card', { align: 'center' });
    doc.moveDown();

    doc.fontSize(11);
    doc.text(`Student: ${data.student.name}`);
    doc.text(`Admission No: ${data.student.admissionNumber}`);
    doc.text(`Class: ${data.student.class}`);
    doc.text(`Term: ${data.term}`);
    doc.text(`Session: ${data.session}`);
    doc.moveDown();

    const tableTop = doc.y;
    const columns = [48, 210, 300, 380, 450, 505];
    doc.font('Helvetica-Bold');
    doc.text('Subject', columns[0], tableTop);
    doc.text('CA', columns[1], tableTop);
    doc.text('Exam', columns[2], tableTop);
    doc.text('Total', columns[3], tableTop);
    doc.text('Grade', columns[4], tableTop);
    doc.text('Remarks', columns[5], tableTop, { width: 70 });
    doc.moveTo(48, tableTop + 18).lineTo(548, tableTop + 18).stroke();

    doc.font('Helvetica');
    let y = tableTop + 28;
    data.subjects.forEach((item) => {
      if (y > 720) {
        doc.addPage();
        y = 48;
      }
      doc.text(item.subject, columns[0], y, { width: 150 });
      doc.text(String(item.assessmentScore), columns[1], y);
      doc.text(String(item.examScore), columns[2], y);
      doc.text(String(item.totalScore), columns[3], y);
      doc.text(item.grade, columns[4], y);
      doc.text(item.remarks || '', columns[5], y, { width: 70 });
      y += 24;
    });

    doc.moveDown(2);
    doc.font('Helvetica-Bold').text(`Average Score: ${data.average}%`);
    doc.text(`Attendance: ${data.attendance.present}/${data.attendance.total} (${data.attendance.percentage}%)`);
    doc.text(`Class Teacher Remarks: ${data.remarks}`);
    doc.moveDown(2);
    doc.font('Helvetica').text('Generated by Smart School Manager', { align: 'right' });
    doc.end();
  });
}

module.exports = { buildReportCard, generateReportCardPdf };
